name: release tag
on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:

  extraction:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Extract tag
        uses: ncipollo/semantic-version-action@v1
        id: tag

  build-push-quayio:
    needs:
      - extraction
    uses: droposhado/workflows/.github/workflows/docker-build-push.yml@main
    with:
      registry: quay.io
      repo: droposhado/bem-te-vi
      platforms: "linux/amd64,linux/arm64"
      tag: ${{ needs.extraction.outputs.tag }}
      push: true
    secrets:
      username: ${{ secrets.QUAYIO_USERNAME }}
      password: ${{ secrets.QUAYIO_PASSWORD }}

  build-push-dockerio:
    needs:
      - extraction
    uses: droposhado/workflows/.github/workflows/docker-build-push.yml@main
    with:
      registry: quay.io
      repo: droposhado/bem-te-vi
      platforms: "linux/amd64,linux/arm64"
      tag: ${{ needs.extraction.outputs.tag }}
      push: true
    secrets:
      username: ${{ secrets.DOCKERIO_USERNAME }}
      password: ${{ secrets.DOCKERIO_PASSWORD }}